-- Insert tools data
INSERT INTO tools (
  name,
  description,
  category,
  url,
  pricing_model,
  features,
  integrations,
  company_stages,
  company_sizes,
  business_models,
  industries,
  rating
) VALUES
-- Hosting & Domains
(
  'Bluehost',
  'Popular web hosting company that also offers domain registration.',
  'Hosting & Domains',
  'https://bluehost.com',
  'subscription',
  ARRAY['Web hosting', 'Domain registration', 'WordPress integration', 'Email hosting', 'SSL certificates'],
  ARRAY['WordPress', 'cPanel', 'CloudFlare', 'Google Workspace'],
  ARRAY['Company Setup', 'Pre-launch', 'Launch/Post Launch'],
  ARRAY['1-10', '11-50'],
  ARRAY['B2B', 'B2C', 'E-commerce'],
  ARRAY['Technology', 'E-commerce', 'Professional Services'],
  4.0
),
(
  'GoDaddy',
  'Largest domain registrar and web hosting company.',
  'Hosting & Domains',
  'https://godaddy.com',
  'subscription',
  ARRAY['Domain registration', 'Web hosting', 'Website builder', 'SSL certificates', 'Professional email'],
  ARRAY['WordPress', 'Microsoft 365', 'Google Workspace', 'Shopify'],
  ARRAY['Company Setup', 'Pre-launch', 'Launch/Post Launch'],
  ARRAY['1-10', '11-50', '51-200'],
  ARRAY['B2B', 'B2C', 'E-commerce'],
  ARRAY['Technology', 'E-commerce', 'Professional Services'],
  4.2
),
(
  'Google Domains',
  'Domain registration service by Google.',
  'Hosting & Domains',
  'https://domains.google',
  'per-domain',
  ARRAY['Domain registration', 'DNS management', 'Email forwarding', 'Privacy protection'],
  ARRAY['Google Workspace', 'Shopify', 'Wix', 'Squarespace'],
  ARRAY['Company Setup', 'Pre-launch'],
  ARRAY['1-10', '11-50'],
  ARRAY['B2B', 'B2C', 'E-commerce'],
  ARRAY['Technology', 'E-commerce', 'Professional Services'],
  4.5
),
-- Email Services
(
  'Google Workspace',
  'Professional email and collaboration tools.',
  'Email Services',
  'https://workspace.google.com',
  'per-user',
  ARRAY['Professional email', 'Calendar', 'Drive storage', 'Meet video conferencing', 'Docs & Sheets'],
  ARRAY['Slack', 'Zoom', 'CRM systems', 'Project management tools'],
  ARRAY['Company Setup', 'Pre-launch', 'Launch/Post Launch'],
  ARRAY['1-10', '11-50', '51-200', '201-500'],
  ARRAY['B2B', 'B2C', 'SaaS'],
  ARRAY['Technology', 'Professional Services', 'Education'],
  4.8
),
(
  'Microsoft 365',
  'Business email and productivity suite.',
  'Email Services',
  'https://microsoft.com/microsoft-365',
  'per-user',
  ARRAY['Outlook email', 'Office apps', 'Teams', 'OneDrive storage', 'SharePoint'],
  ARRAY['Dynamics 365', 'Power BI', 'Azure', 'Third-party apps'],
  ARRAY['Company Setup', 'Pre-launch', 'Launch/Post Launch'],
  ARRAY['1-10', '11-50', '51-200', '201-500', '501+'],
  ARRAY['B2B', 'B2C', 'Enterprise'],
  ARRAY['Technology', 'Professional Services', 'Enterprise'],
  4.7
),
-- Legal Services
(
  'LegalZoom',
  'Online legal services platform.',
  'Legal Services',
  'https://legalzoom.com',
  'per-service',
  ARRAY['Business formation', 'Registered agent', 'Trademark registration', 'Legal documents', 'Attorney consultations'],
  ARRAY['QuickBooks', 'Business licenses', 'Compliance services'],
  ARRAY['Company Setup', 'Pre-launch'],
  ARRAY['1-10', '11-50'],
  ARRAY['B2B', 'B2C'],
  ARRAY['Professional Services', 'Technology', 'E-commerce'],
  4.3
),
(
  'Stripe Atlas',
  'All-in-one platform for incorporating in the US.',
  'Legal Services',
  'https://stripe.com/atlas',
  'one-time',
  ARRAY['Delaware C Corp formation', 'EIN registration', 'Bank account setup', 'Stripe account', 'Legal templates'],
  ARRAY['Stripe Payments', 'Banking services', 'Tax tools'],
  ARRAY['Company Setup'],
  ARRAY['1-10'],
  ARRAY['B2B', 'B2C', 'SaaS', 'E-commerce'],
  ARRAY['Technology', 'E-commerce', 'FinTech'],
  4.6
),
-- Financial Services
(
  'Brex',
  'Financial services platform for startups.',
  'Financial Services',
  'https://brex.com',
  'freemium',
  ARRAY['Business bank account', 'Credit card', 'Expense management', 'Bill pay', 'Rewards'],
  ARRAY['QuickBooks', 'Xero', 'NetSuite', 'Expensify'],
  ARRAY['Company Setup', 'Pre-launch', 'Launch/Post Launch'],
  ARRAY['1-10', '11-50', '51-200'],
  ARRAY['B2B', 'SaaS', 'Technology'],
  ARRAY['Technology', 'SaaS', 'E-commerce'],
  4.7
),
(
  'Mercury',
  'Digital banking for startups.',
  'Financial Services',
  'https://mercury.com',
  'free',
  ARRAY['Business checking', 'Savings accounts', 'Team cards', 'API access', 'Wire transfers'],
  ARRAY['QuickBooks', 'Xero', 'Wise', 'Zapier'],
  ARRAY['Company Setup', 'Pre-launch', 'Launch/Post Launch'],
  ARRAY['1-10', '11-50', '51-200'],
  ARRAY['B2B', 'SaaS', 'Technology'],
  ARRAY['Technology', 'SaaS', 'E-commerce'],
  4.8
),
-- Marketing
(
  'Mailchimp',
  'Email marketing and automation platform.',
  'Marketing',
  'https://mailchimp.com',
  'freemium',
  ARRAY['Email campaigns', 'Marketing automation', 'Landing pages', 'CRM', 'Analytics'],
  ARRAY['Shopify', 'WooCommerce', 'Salesforce', 'WordPress'],
  ARRAY['Pre-launch', 'Launch/Post Launch'],
  ARRAY['1-10', '11-50', '51-200'],
  ARRAY['B2B', 'B2C', 'E-commerce'],
  ARRAY['E-commerce', 'Technology', 'Professional Services'],
  4.5
),
(
  'Semrush',
  'SEO and digital marketing platform.',
  'Marketing',
  'https://semrush.com',
  'subscription',
  ARRAY['Keyword research', 'Competitor analysis', 'Site audit', 'Content marketing', 'PPC research'],
  ARRAY['Google Analytics', 'Google Search Console', 'WordPress', 'Trello'],
  ARRAY['Pre-launch', 'Launch/Post Launch'],
  ARRAY['1-10', '11-50', '51-200'],
  ARRAY['B2B', 'B2C', 'E-commerce'],
  ARRAY['Technology', 'E-commerce', 'Marketing'],
  4.7
),
-- Development
(
  'Vercel',
  'Frontend deployment and hosting platform.',
  'Development',
  'https://vercel.com',
  'freemium',
  ARRAY['Frontend deployment', 'Serverless functions', 'Edge network', 'Preview deployments', 'Analytics'],
  ARRAY['GitHub', 'GitLab', 'Bitbucket', 'Next.js'],
  ARRAY['Planning & Development', 'Pre-launch', 'Launch/Post Launch'],
  ARRAY['1-10', '11-50', '51-200'],
  ARRAY['B2B', 'SaaS', 'Technology'],
  ARRAY['Technology', 'SaaS', 'E-commerce'],
  4.8
),
(
  'DigitalOcean',
  'Cloud infrastructure provider.',
  'Development',
  'https://digitalocean.com',
  'usage-based',
  ARRAY['Cloud servers', 'Managed databases', 'Kubernetes', 'Object storage', 'Load balancers'],
  ARRAY['GitHub', 'Docker', 'Kubernetes', 'Terraform'],
  ARRAY['Planning & Development', 'Pre-launch', 'Launch/Post Launch'],
  ARRAY['1-10', '11-50', '51-200'],
  ARRAY['B2B', 'SaaS', 'Technology'],
  ARRAY['Technology', 'SaaS', 'Development'],
  4.6
);